root: true

parser: '@typescript-eslint/parser'

env:
  browser: true
  node: true
  es2020: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

plugins:
  - '@typescript-eslint'

rules:
  '@typescript-eslint/no-namespace': 0
