name: Docs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: yarn
      - name: Build
        run: yarn docs:build
      - name: Deploy vercel
        if: ${{ github.repository == 'nonebotjs/koishi-plugin-nonebot' && github.ref == 'refs/heads/main' }}
        run: vercel deploy docs/.vitepress/dist --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
